services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./backend:/usr/app/backend
      - /usr/app/backend/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gazin

  pgadmin:
    container_name: pgadmin
    depends_on:
      - postgres
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8002:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=danielrossini7@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    volumes:
      - ./db/postgresql/pgadmin:/var/lib/pgadmin 
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./frontend:/usr/app/frontend
      - /usr/app/frontend/node_modules
    depends_on:
      - backend